name: Checkout2

on:
  pull_request:
    branches:
      - master
      - production
    types:
      - closed

jobs:
  checkout:
    if: github.event.pull_request.merged == true
    name: Checkout
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/checkout2

<<<<<<< HEAD
  checkout3:
    uses: ./.github/reusable/checkout3.yaml

=======


>>>>>>> 36791b97ad0833cba2bd8f87d32cf71bfe5e6f07